In [ ]:
#variable
a=10
print("Iam",a," years old")

Iam 10  years old


In [ ]:
#aeithimatic  2 number int variable
a=int(input("enter a value"))
b=int(input("enter bvalue"))
c=a+b
print(c)
print("Difference is",a-b)
print("product is",a*b)
print("quotient is",a/b)
print("remainderis",a%b)
print("Power of a to be is ",a**b)
print("Floor division is",a//b)2

enter a value6548
enter bvalue583
7131
Difference is 5965
product is 3817484
quotient is 11.231560891938251
remainderis 135
Power of a to be is  618521843125013935671662938956689575715869579847405411844662783491631542187818112804487996461039984300581140592555012886743196359008748462635131687357941178567182957080043172074306821422560165827377507979908304064213014394252995046758073480606229826654352213630100597928513265848941169540019816797687671550516953638193883812353961045249058831716216666187426769532050214615405225111384764295638543462306323724646843562183220878187100468623441647194188501617241407396959005295499839135443273107843363332824555791879732892947349028897326056957590085299354220731273249790399066501829976866778233499356600949002509906695722038691882903516691723135656284173497207320653888192478421075587468813288167453941143243584728475772271329594526131908297461358661488216818700291998115839955327091170187922043411237116594436965050569192030504461878968334214319072112083878

In [ ]:
#take a number from the user which is the salary .if the salary is more than 50000,there is a 10% tax deduction.print the final salary
s=int(input("enter salary"))
if(s>=50000):
  tax=s*(10/100)
  s=s-tax
  print("final salary is:",s)
else:
    print("your salary is less than 50000 no tax deduction")


enter salary30000
your salary is less than 50000 no tax deduction


In [ ]:
#get the salary from the user if yhe salary is more are equal to 50k .apply 10% tax deduction if the salary is less than 50k apply 5% tax . if the  salary is more than 70k .apply 12% tax. if the salary exisit 1lakh print you are promoted  next level .
s=int(input("enter salary"))
if(s<=50000):
  s=s-(s*(5/100))
  print("final salary is:",s)
elif(s>50000 and s<=70000):
  s=s-(s*(10/100))
  print("salary is ",s)
elif(s>70000 and s<100000):
  s=s-(s*(12/100))
  print("salary is",s)
else:
  print("you are promoted")



enter salary100000
you are promoted


In [ ]:
r=range(1,11)
n=int(input("enter numbmer:"))
for i in r:
  print(n,"X",i,"=",i*n)



enter numbmer:29
29 X 1 = 29
29 X 2 = 58
29 X 3 = 87
29 X 4 = 116
29 X 5 = 145
29 X 6 = 174
29 X 7 = 203
29 X 8 = 232
29 X 9 = 261
29 X 10 = 290


In [ ]:
#while
a=int(input("enter a"))
i=1
while(i<11):
  print(n,"x",i,"=",i*n)
  i=i+1

enter a254
29 x 1 = 29
29 x 2 = 58
29 x 3 = 87
29 x 4 = 116
29 x 5 = 145
29 x 6 = 174
29 x 7 = 203
29 x 8 = 232
29 x 9 = 261
29 x 10 = 290


In [ ]:
#list:
l1=[1,8,5,"charvi"]
print(l1[1:3])

[8, 5]


In [ ]:
#create a heterogeneous list
l1=[1,"kill",89,"chat",9.1,True]
for i in l1:
  print(i)

1
kill
89
chat
9.1
True


In [ ]:
#mutable:
l1.append("appended") #add element at back of list
print(l1)
l1.insert(4,10)#listname.insert(index,element)
print(l1)

[1, 'kill', 89, 'chat', 10, 9.1, True, 'appended', 'appended', 'appended', 'appended', 'appended', 'appended']
[1, 'kill', 89, 'chat', 10, 10, 9.1, True, 'appended', 'appended', 'appended', 'appended', 'appended', 'appended']


In [ ]:
#append or extend  #list1.extend(list2)
l2=["insta",9,"cahrvi",17] #or 1.expend(1>2)
l1.extend(l2)#l1=l1+l2
print(l1)

[1, 'kill', 89, 'chat', 10, 10, 9.1, True, 'appended', 'appended', 'appended', 'appended', 'appended', 'appended', 'insta', 9, 'cahrvi', 17]


In [ ]:
#remove
l2.remove("insta")  #listname.delete(element)
print(l2)

[9, 17]


In [ ]:
#pop
l3=[29,"chinna",3,4]
l3.pop(2)    #listname.pop(index)
print(23)

23


In [ ]:
#clear()
l1.clear()
print(l1)

[]


In [ ]:
#create a lsit of 10 integers elements print there squares. save these squares in new list
l=[1,209,123,4,53,656,73,8,9,10]
l2=[]
for i in l:
  l2.append(i**2)
print(l2)

[1, 43681, 15129, 16, 2809, 430336, 5329, 64, 81, 100]


In [ ]:
#List comprension
#newlist =[output for if]
l=[209,123,4,53,656,73,8,9,10]
l2=[i*i for i in l if i>50]
print(l2)

[43681, 15129, 2809, 430336, 5329]


In [ ]:
#List comprension
#newlist =[(st of if) if(cond)else(st of else for)]
l=[23,67,12,34,69]
l2=[i*i if i>50 else 'X' for i in l ]
print(l2)

['X', 4489, 'X', 'X', 4761]


In [ ]:
#take salary from user if the salary is less than 50k,10% tax.otherwisw 15%tax
n=int(input("enter salary"))
l=[n-n*(0.5)if(n<50000) else n-n*(1.5)]
print(l)

enter salary45000
[22500.0]


In [ ]:
l1=[20000,40000,70000,90000]
l=[n-(n*0.1)if(n<=50000) else n-(n*0.15) for n in l1]
print(l)

[18000.0, 36000.0, 59500.0, 76500.0]


In [ ]:
#dictionary
dict1={"Mentor":'jwalitha',34:'Likitha',35:'Ramya',37:'Lavanya',58:"Dhanush"}
print(dict1)
print(dict1.keys())
print(dict1.values)

{'Mentor': 'jwalitha', 34: 'Likitha', 35: 'Ramya', 37: 'Lavanya', 58: 'Dhanush'}
dict_keys(['Mentor', 34, 35, 37, 58])
<built-in method values of dict object at 0x7838dca41340>


In [ ]:
dict1={"Mentor":"jwalitha",34:"Likitha",35:"Ramya",37:"Lavanya",58:"Dhanush"}
print(dict1[34])

Likitha


In [ ]:
dict3={"Dept":"CSE","details":{"year":"II","sec":"D","count":71}}
print("year is",dict3["details"]["year"])
print("section is",dict3["details"]["sec"])
print("strenght is",dict3["details"]["count"])


year is II
section is D
strenght is 71


In [ ]:
idl=[34,56,78,39,100]
name=["Joe","Suji","Rohini","Shankar","main"]
new_zip=(zip(idl,name))
for i in new_zip:
  print(i)

(34, 'Joe')
(56, 'Suji')
(78, 'Rohini')
(39, 'Shankar')
(100, 'main')


In [ ]:
idl=[34,56,78,39,100]
name=["Joe","Suji","Rohini","Shankar","main"]
new_zip=(zip(idl,name))
print(dict(zip(idl,name)))


{34: 'Joe', 56: 'Suji', 78: 'Rohini', 39: 'Shankar', 100: 'main'}


In [ ]:
#Numpy
import numpy as np
A=np.array([1,2,3,4])#1d array
print(A.ndim)
print(A.shape)


1
(4,)


In [ ]:
#create a 2 dimensional array
B=np.array([[1,2,3,4],['a','b','c','d'],['@','#','$','%']])
print(B)
print(B.ndim)
print(B.shape)



[['1' '2' '3' '4']
 ['a' 'b' 'c' 'd']
 ['@' '#' '$' '%']]
2
(3, 4)


In [ ]:
#create a 3 dimesional array
C=np.array([[[1,2,3],[4,5,6]],[[77,44,23],[22,98,7]]])
print(C)
print(C.ndim)
print(C.shape)


[[[ 1  2  3]
  [ 4  5  6]]

 [[77 44 23]
  [22 98  7]]]
3
(2, 2, 3)


In [ ]:
 z=np.ones((2,4,3))#g,r,c
 print(z)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
 z=np.zeros((2,4,3))#(g,r,c)
 print(z)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
y=np.arange(1,10,2)#start,stop,step
print(y)
print(type(y))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the number that divisible by 8 using arange b/w 1 to 1000
l=np.arange(8,1000,8)
print(l)
print(type(l))

[  8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136 144
 152 160 168 176 184 192 200 208 216 224 232 240 248 256 264 272 280 288
 296 304 312 320 328 336 344 352 360 368 376 384 392 400 408 416 424 432
 440 448 456 464 472 480 488 496 504 512 520 528 536 544 552 560 568 576
 584 592 600 608 616 624 632 640 648 656 664 672 680 688 696 704 712 720
 728 736 744 752 760 768 776 784 792 800 808 816 824 832 840 848 856 864
 872 880 888 896 904 912 920 928 936 944 952 960 968 976 984 992]
<class 'numpy.ndarray'>


In [ ]:
#spliting a range of number having common differnce
q=np.linspace(33,45,21)
print(q)

[33.  33.6 34.2 34.8 35.4 36.  36.6 37.2 37.8 38.4 39.  39.6 40.2 40.8
 41.4 42.  42.6 43.2 43.8 44.4 45. ]


In [ ]:
#