In [ ]:
#variable
a=10
print("Iam",a," years old")

Iam 10  years old


In [1]:
#aeithimatic  2 number int variable
a=int(input("enter a value"))
b=int(input("enter bvalue"))
c=a+b
print(c)
print("Difference is",a-b)
print("product is",a*b)
print("quotient is",a/b)
print("remainderis",a%b)
print("Power of a to be is ",a**b)
print("Floor division is",a//b)

enter a value35
enter bvalue15
50
Difference is 20
product is 525
quotient is 2.3333333333333335
remainderis 5
Power of a to be is  144884079282928466796875
Floor division is 2


In [ ]:
#take a number from the user which is the salary .if the salary is more than 50000,there is a 10% tax deduction.print the final salary
s=int(input("enter salary"))
if(s>=50000):
  tax=s*(10/100)
  s=s-tax
  print("final salary is:",s)
else:
    print("your salary is less than 50000 no tax deduction")


enter salary30000
your salary is less than 50000 no tax deduction


In [ ]:
#get the salary from the user if yhe salary is more are equal to 50k .apply 10% tax deduction if the salary is less than 50k apply 5% tax . if the  salary is more than 70k .apply 12% tax. if the salary exisit 1lakh print you are promoted  next level .
s=int(input("enter salary"))
if(s<=50000):
  s=s-(s*(5/100))
  print("final salary is:",s)
elif(s>50000 and s<=70000):
  s=s-(s*(10/100))
  print("salary is ",s)
elif(s>70000 and s<100000):
  s=s-(s*(12/100))
  print("salary is",s)
else:
  print("you are promoted")



enter salary100000
you are promoted


In [ ]:
r=range(1,11)
n=int(input("enter numbmer:"))
for i in r:
  print(n,"X",i,"=",i*n)



enter numbmer:29
29 X 1 = 29
29 X 2 = 58
29 X 3 = 87
29 X 4 = 116
29 X 5 = 145
29 X 6 = 174
29 X 7 = 203
29 X 8 = 232
29 X 9 = 261
29 X 10 = 290


In [7]:
#while
a=int(input("enter a"))
i=1
while(i<11):
  print(a,"x",i,"=",i*a)
  i=i+1

enter a235
235 x 1 = 235
235 x 2 = 470
235 x 3 = 705
235 x 4 = 940
235 x 5 = 1175
235 x 6 = 1410
235 x 7 = 1645
235 x 8 = 1880
235 x 9 = 2115
235 x 10 = 2350


In [ ]:
#list:
l1=[1,8,5,"charvi"]
print(l1[1:3])

[8, 5]


In [ ]:
#create a heterogeneous list
l1=[1,"kill",89,"chat",9.1,True]
for i in l1:
  print(i)

1
kill
89
chat
9.1
True


In [ ]:
#mutable:
l1.append("appended") #add element at back of list
print(l1)
l1.insert(4,10)#listname.insert(index,element)
print(l1)

[1, 'kill', 89, 'chat', 10, 9.1, True, 'appended', 'appended', 'appended', 'appended', 'appended', 'appended']
[1, 'kill', 89, 'chat', 10, 10, 9.1, True, 'appended', 'appended', 'appended', 'appended', 'appended', 'appended']


In [ ]:
#append or extend  #list1.extend(list2)
l2=["insta",9,"cahrvi",17] #or 1.expend(1>2)
l1.extend(l2)#l1=l1+l2
print(l1)

[1, 'kill', 89, 'chat', 10, 10, 9.1, True, 'appended', 'appended', 'appended', 'appended', 'appended', 'appended', 'insta', 9, 'cahrvi', 17]


In [ ]:
#remove
l2.remove("insta")  #listname.delete(element)
print(l2)

[9, 17]


In [ ]:
#pop
l3=[29,"chinna",3,4]
l3.pop(2)    #listname.pop(index)
print(23)

23


In [ ]:
#clear()
l1.clear()
print(l1)

[]


In [ ]:
#create a lsit of 10 integers elements print there squares. save these squares in new list
l=[1,209,123,4,53,656,73,8,9,10]
l2=[]
for i in l:
  l2.append(i**2)
print(l2)

[1, 43681, 15129, 16, 2809, 430336, 5329, 64, 81, 100]


In [ ]:
#List comprension
#newlist =[output for if]
l=[209,123,4,53,656,73,8,9,10]
l2=[i*i for i in l if i>50]
print(l2)

[43681, 15129, 2809, 430336, 5329]


In [71]:
#List comprension
#newlist =[(st of if) if(cond)else(st of else for)]
l=[23,67,12,34,69]
l2=[i*i if i>50 else 'X' for i in l ]
print(l2)

['X', 4489, 'X', 'X', 4761]


In [72]:
#take salary from user if the salary is less than 50k,10% tax.otherwisw 15%tax
n=int(input("enter salary"))
l=[n-n*(0.5)if(n<50000) else n-n*(1.5)]
print(l)

enter salary45000
[22500.0]


In [79]:
l1=[20000,40000,70000,90000]
l=[n-(n*0.1)if(n<=50000) else n-(n*0.15) for n in l1]
print(l)

[18000.0, 36000.0, 59500.0, 76500.0]


In [85]:
#dictionary
dict1={"Mentor":'jwalitha',34:'Likitha',35:'Ramya',37:'Lavanya',58:"Dhanush"}
print(dict1)
print(dict1.keys())
print(dict1.values)

{'Mentor': 'jwalitha', 34: 'Likitha', 35: 'Ramya', 37: 'Lavanya', 58: 'Dhanush'}
dict_keys(['Mentor', 34, 35, 37, 58])
<built-in method values of dict object at 0x7838dca41340>


In [101]:
dict1={"Mentor":"jwalitha",34:"Likitha",35:"Ramya",37:"Lavanya",58:"Dhanush"}
print(dict1[34])

Likitha


In [94]:
dict3={"Dept":"CSE","details":{"year":"II","sec":"D","count":71}}
print("year is",dict3["details"]["year"])
print("section is",dict3["details"]["sec"])
print("strenght is",dict3["details"]["count"])


year is II
section is D
strenght is 71


In [98]:
idl=[34,56,78,39,100]
name=["Joe","Suji","Rohini","Shankar","main"]
new_zip=(zip(idl,name))
for i in new_zip:
  print(i)

(34, 'Joe')
(56, 'Suji')
(78, 'Rohini')
(39, 'Shankar')
(100, 'main')


In [99]:
idl=[34,56,78,39,100]
name=["Joe","Suji","Rohini","Shankar","main"]
new_zip=(zip(idl,name))
print(dict(zip(idl,name)))


{34: 'Joe', 56: 'Suji', 78: 'Rohini', 39: 'Shankar', 100: 'main'}


In [103]:
#Numpy
import numpy as np
A=np.array([1,2,3,4])#1d array
print(A.ndim)
print(A.shape)


1
(4,)


In [106]:
#create a 2 dimensional array
B=np.array([[1,2,3,4],['a','b','c','d'],['@','#','$','%']])
print(B)
print(B.ndim)
print(B.shape)



[['1' '2' '3' '4']
 ['a' 'b' 'c' 'd']
 ['@' '#' '$' '%']]
2
(3, 4)


In [109]:
#create a 3 dimesional array
C=np.array([[[1,2,3],[4,5,6]],[[77,44,23],[22,98,7]]])
print(C)
print(C.ndim)
print(C.shape)


[[[ 1  2  3]
  [ 4  5  6]]

 [[77 44 23]
  [22 98  7]]]
3
(2, 2, 3)


In [110]:
 z=np.ones((2,4,3))#g,r,c
 print(z)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [112]:
 z=np.zeros((2,4,3))#(g,r,c)
 print(z)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [114]:
x=np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
y=np.arange(1,10,2)#start,stop,step
print(y)
print(type(y))

NameError: name 'np' is not defined

In [4]:
#print all the number that divisible by 8 using arange b/w 1 to 1000
l=np.arange(8,1000,8)
print(l)
print(type(l))

NameError: name 'np' is not defined

In [6]:
#spliting a range of number having common differnce
q=np.linspace(3,2,12)
print(q)


NameError: name 'np' is not defined

In [ ]:
#