In [ ]:
import numpy as np
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
B=np.linspace(2,4,6).reshape(2,3)
print(B)

[[2.  2.4 2.8]
 [3.2 3.6 4. ]]


In [ ]:
C=np.array([1,2,3,4,5,99,12,78]).reshape(2,2,2,)
print(C)

[[[ 1  2]
  [ 3  4]]

 [[ 5 99]
  [12 78]]]


[11 21 84 57]


In [ ]:
A=np.array([14,25,89,64])
B=np.array([3,4,5,7])
C=A+B
print(C)

[17 29 94 71]


In [ ]:
#martix multiplication
A=np.array([14,25,89,64]).reshape(2,2)
B=np.array([3,4,5,7]).reshape(2,2)
print(A)
print(b)
C=A@B
print(C)

[[14 25]
 [89 64]]
[1, 5, 6, 7, 8]
[[167 231]
 [587 804]]


In [ ]:
#martix multiplication
A=np.array([14,25,89,64]).reshape(2,2)
B=np.array([3,4,5,7]).reshape(2,2)
print(A)
print(b)
C=A.dot(B)
print(C)

[[14 25]
 [89 64]]
[1, 5, 6, 7, 8]
[[167 231]
 [587 804]]


In [ ]:
#max &min
a=np.array([43,31,65,78,8])
print(a.max())
print(a.min())

78
8


In [ ]:
b=np.array([43,31,65,78]).reshape(2,2)
print(b)
print(b.max(axis=0)))#column wise bigger number
print(b.max(axis=1))#row wise bigger number

[[43 31]
 [65 78]]
[65 78]
[43 78]


In [ ]:
b=np.array([43,31,65,78]).reshape(2,2)
print(b)
print(b.min(axis=0))#axis 0- colum lower
print(b.min(axis=1))#row wise lower number axis-1

[[43 31]
 [65 78]]
[43 31]
[31 65]


In [ ]:
#joing arrays
a=np.array([43,31,65,78]).reshape(2,2)
b=np.array([4,11,35,28]).reshape(2,2)
print(a)
print(b)
print(np.vstack((a,b)))

[[43 31]
 [65 78]]
[[ 4 11]
 [35 28]]
[[43 31]
 [65 78]
 [ 4 11]
 [35 28]]


In [ ]:
a=np.array([43,31,65,78]).reshape(2,2)
b=np.array([4,11,35,28]).reshape(2,2)
print(a)
print(b)
print(np.stack((a,b),axis=0))

[[43 31]
 [65 78]]
[[ 4 11]
 [35 28]]
[[[43 31]
  [65 78]]

 [[ 4 11]
  [35 28]]]


In [ ]:
a=np.array([43,31,65,78]).reshape(2,2)
b=np.array([4,11,35,28]).reshape(2,2)
print(a)
print(b)
print(np.stack((a,b),axis=1))

[[43 31]
 [65 78]]
[[ 4 11]
 [35 28]]
[[[43 31]
  [ 4 11]]

 [[65 78]
  [35 28]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("After dstack")
print(np.dstack(a))#no.of row -->no.of groups
#no.of colum in every group -->no.of rows in every group
#[0 0],[1 1]...............

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
 #splitting arrays!
a=np.arange(18).reshape(6,3)
print(a)
print(np.vsplit(a,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print(np.vsplit(a,(2,5)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]


In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print(np.vsplit(a,(2,5)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]


In [ ]:
a=np.linspace(17,4,18).reshape(3,6)
print(a)
print(a.argmax())

[[17.         16.23529412 15.47058824 14.70588235 13.94117647 13.17647059]
 [12.41176471 11.64705882 10.88235294 10.11764706  9.35294118  8.58823529]
 [ 7.82352941  7.05882353  6.29411765  5.52941176  4.76470588  4.        ]]
0


In [ ]:
a=np.array([17,4,18,91]).reshape(2,2)
print(a)
print(a.argmax())

[[17  4]
 [18 91]]
3


In [ ]:
a=np.array([17,4,18,91]).reshape(2,2)
print(a)
print(a.argmax(axis=0))#opsition[0 0 0 0
                                      1 1 1  1]

[[17  4]
 [18 91]]
[1 1]


In [ ]:
a=np.array([17,4,18,91]).reshape(2,2)
print(a)
print(a.argmax(axis=1))#opsition[0 1 2 3
                                           0 1 2 3]

[[17  4]
 [18 91]]
[0 1]


In [ ]:
a=np.array([17,4,18,91]).reshape(2,2)
print(a)
print(a.argmin())

[[17  4]
 [18 91]]
1


STATISTICS


In [ ]:
#Mean,Median,std,variance
A=[12,34,67,89,23]
print("Mean:",np.mean(A))
print("Median:",np.median(A))
print("Variance:",np.var(A))
print("Standard devition:",np.std(A))

Mean: 45.0
Median: 34.0
Variance: 822.8
Standard devition: 28.684490582891655


THIGONOMERTY

In [ ]:
#PI value
print(np.pi)
print(a)#radians
print(np.rad2deg(a))#converts radians to degree

3.141592653589793
[[17  4]
 [18 91]]
[[ 974.02825172  229.18311805]
 [1031.32403124 5213.91593569]]


In [ ]:
#radians to degree conversion
A=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi/1])
print(np.rad2deg(A))#convert radians to degree

[ 45.  60.  90. 180.]


In [ ]:
#degree to radians coversion
r=np.array([20,30,44,50,12,67])
c=np.deg2rad(r)
print(c)

[0.34906585 0.52359878 0.76794487 0.87266463 0.20943951 1.1693706 ]


In [ ]:
np.sin(r)

array([ 0.91294525, -0.98803162,  0.01770193, -0.26237485, -0.53657292,
       -0.85551998])

In [ ]:
np.cos(r)

array([ 0.40808206,  0.15425145,  0.99984331,  0.96496603,  0.84385396,
       -0.5177698 ])

In [ ]:
np.tan(c)

array([0.36397023, 0.57735027, 0.96568877, 1.19175359, 0.21255656,
       2.35585237])

In [ ]:
np.arcsin(1) #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1) #cos^-1

0.0

In [ ]:
np.arctan(1) #tan^-1

0.7853981633974483

In [ ]:
#hypotneuse
a=12
b=3
print(np.hypot(a,b))

12.36931687685298


SEARCHING!

In [ ]:
A=np.array([52,78,12,45,63,54])
print(np.where(A==12))

(array([2]),)


In [ ]:
A=np.array([52,78,12,45,63,54])
print(np.where(A%2==0))#even

(array([0, 1, 2, 5]),)


In [ ]:
A=np.array([22,13,55,67,89,43])
print(np.searchsorted(A,22))

2


In [ ]:
A=np.array([5,8,74,14])
B=np.array([50,7,88,1])
print("Sum: ",np.add(A,B))
print("Difference:",np.subtract(A,B))
print("Product:",np.multiply(A,B))
print("Quotient:",np.divide(A,B))
print("Remainder:",np.mod(A,B))
print(np.divmod(A,B))

Sum:  [ 55  15 162  15]
Difference: [-45   1 -14  13]
Product: [ 250   56 6512   14]
Quotient: [ 0.1         1.14285714  0.84090909 14.        ]
Remainder: [ 5  1 74  0]
(array([ 0,  1,  0, 14]), array([ 5,  1, 74,  0]))


In [ ]:
A=np.array([5,8,6,8,5])
print(np.sort(A))

[5 5 6 8 8]


In [ ]:
A=np.array([5,3,6,54])
B=np.array([52,22,44,55,])
print(np.setdiff1d(A,B))

[ 3  5  6 54]


In [ ]:
A=np.array([5,3,6,54])
B=np.array([52,22,44,55,])
print(np.intersect1d(A,B))

[]


ROUNDING

In [ ]:
a=np.trunc([2.234454,-9876])
print(a)

[ 2.000e+00 -9.876e+03]


In [ ]:
a=np.around([2.234454,9])
print(a)

[2. 9.]


In [ ]:
a=np.floor([2.234454,-9876])
print(a)

[ 2.000e+00 -9.876e+03]


In [ ]:
a=np.ceil([2.234454,-9876])
print(a)

[ 3.000e+00 -9.876e+03]


MORE FUNCTION

In [ ]:
#comulative sum
A=np.array([3,6,87,22,3])
print(np.cumsum(a))

[ 3.000e+00 -9.873e+03]


In [ ]:
#comulative product
A=np.array([3,6,87,22,3])
print(np.cumprod(a))

[ 3.0000e+00 -2.9628e+04]


In [ ]:
#LCM &GCD,
print(np.lcm(24,35))
print(np.gcd(85,65))

840
5


In [ ]:
#LCM&GCD
a=np.array([6,8,9,22,12,3])
print("LCM",np.lcm.reduce(a))
print("GCD",np.gcd.reduce(a))

LCM 792
GCD 1


In [ ]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
from numpy import random as rd

A=rd.rand(10) #rand(n) #default limit 0to 0.99
print(a)